pharmapp/pharmapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from. import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('wholesale/', include('wholesale.urls')),
    path('userauth/', include('userauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pharmapp/store/urls.py
from django.urls import path, register_converter
from.converters import ShortUUIDConverter
from . import views


# Register the ShortUUIDConverter
register_converter(ShortUUIDConverter, 'shortuuid')


app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('store/', views.store, name='store'),
    path('search_item/', views.search_item, name='search_item'),
    path('add_item/', views.add_item, name='add_item'),
    path('edit_item/<int:pk>/', views.edit_item, name='edit_item'),
    path('return_item/<int:pk>/', views.return_item, name='return_item'),
    path('delete_item/<int:pk>/', views.delete_item, name='delete_item'),
    path('dispense/', views.dispense, name='dispense'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('view_cart/', views.view_cart, name='view_cart'),
    path('update_cart_quantity/<int:pk>/', views.update_cart_quantity, name='update_cart_quantity'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('receipt/', views.receipt, name='receipt'),
    path('receipts/<str:receipt_id>/', views.receipt_detail, name='receipt_detail'),
    path('register_customers/', views.register_customers, name='register_customers'),
    path('customer_list/', views.customer_list, name='customer_list'),
    path('edit_customer/<int:pk>/', views.edit_customer, name='edit_customer'),
    path('customers_on_negative/', views.customers_on_negative, name='customers_on_negative'),
    path('wallet_details/<int:pk>/', views.wallet_details, name='wallet_details'),
    path('add_funds/<int:pk>/', views.add_funds, name='add_funds'),
    path('reset_wallet/<int:pk>/', views.reset_wallet, name='reset_wallet'),
    path('delete_customer/<int:pk>/', views.delete_customer, name='delete_customer'),
    path('select_items/<int:pk>/', views.select_items, name='select_items'),
    path('dispensing_log/', views.dispensing_log, name='dispensing_log'),
    path('receipt_list/', views.receipt_list, name='receipt_list'),
    path('search_receipts/', views.search_receipts, name='search_receipts'),
    path('daily_sales/', views.daily_sales, name='daily_sales'),
    path('monthly_sales/', views.monthly_sales, name='monthly_sales'),
    path('sales_by_user/', views.sales_by_user, name='sales_by_user'),
    path('exp_date_alert/', views.exp_date_alert, name='exp_date_alert'),
    path('customer_history/<int:pk>/', views.customer_history, name='customer_history'),
    path('register_supplier_view/', views.register_supplier_view, name='register_supplier_view'),
    path('list_suppliers_view/', views.list_suppliers_view, name='supplier_list'),
    path('procurement_list/', views.procurement_list, name='procurement_list'),
    path('add_procurement/', views.add_procurement, name='add_procurement'),
    path('search_procurement/', views.search_procurement, name='search_procurement'),
    path('procurement_detail/<int:procurement_id>/', views.procurement_detail, name='procurement_detail'),
    path('suppliers/', views.list_suppliers_view, name='list_suppliers'),
    
]

pharmapp/store/models.py
from django.utils.dateparse import parse_date
from decimal import Decimal
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_delete
from customer.models import Customer, WholesaleCustomer, TransactionHistory
from datetime import datetime
from shortuuid.django_fields import ShortUUIDField
from userauth.models import User





# Create your models here.
DOSAGE_FORM = [
    ('Tablet', 'Tablet'),
    ('Capsule', 'Capsule'),
    ('Cream', 'Cream'),
    ('Consumable', 'Consumable'),
    ('Injection', 'Injection'),
    ('Infusion', 'Infusion'),
    ('Inhaler', 'Inhaler'),
    ('Suspension', 'Suspension'),
    ('Syrup', 'Syrup'),
    ('Eye-drop', 'Eye-drop'),
    ('Ear-drop', 'Ear-drop'),
    ('Eye-ointment', 'Eye-ointment'),
    ('Rectal', 'Rectal'),
    ('Vaginal', 'Vaginal'),
]


UNIT = [
    ('Amp', 'Amp'),
    ('Bottle', 'Bottle'),
    ('Tab', 'Tab'),
    ('Tin', 'Tin'),
    ('Caps', 'Caps'),
    ('Card', 'Card'),
    ('Carton', 'Carton'),
    ('Pack', 'Pack'),
    ('Pcs', 'Pcs'),
    ('Roll', 'Roll'),
    ('Vail', 'Vail'),
    ('1L', '1L'),
    ('2L', '2L'),
    ('4L', '4L'),
]

MARKUP_CHOICES = [
        (0, 'No markup'),
        (2.5, '2.5% markup'),
        (5, '5% markup'),
        (7.5, '7.5% markup'),
        (10, '10% markup'),
        (12.5, '12.5% markup'),
        (15, '15% markup'),
        (17.5, '17.5% markup'),
        (20, '20% markup'),
        (22.5, '22.5% markup'),
        (25, '25% markup'),
        (27.5, '27.5% markup'),
        (30, '30% markup'),
        (32.5, '32.5% markup'),
        (35, '35% markup'),
        (37.5, '37.5% markup'),
        (40, '40% markup'),
        (42.5, '42.5% markup'),
        (45, '45% markup'),
        (47.5, '47.5% markup'),
        (50, '50% markup'),
        (57.5, '57.5% markup'),
        (60, '60% markup'),
        (62.5, '62.5% markup'),
        (65, '65% markup'),
        (67.5, '67.5% markup'),
        (70, '70% markup'),
        (72., '72.% markup'),
        (75, '75% markup'),
        (77.5, '77.5% markup'),
        (80, '80% markup'),
        (82.5, '82.% markup'),
        (85, '85% markup'),
        (87.5, '87.5% markup'),
        (90, '90% markup'),
        (92., '92.% markup'),
        (95, '95% markup'),
        (97.5, '97.5% markup'),
        (100, '100% markup'),
    ]


STATUS_CHOICES = [
        ('Returned', 'Returned'),
        ('Partially Returned', 'Partially Returned'),
        ('Dispensed', 'Dispensed'),
    ]

class Formulation(models.Model):
    dosage_form = models.CharField(max_length=200, choices=DOSAGE_FORM, null=True, blank=True, default='DosageForm')
    
    def __str__(self):
        return self.dosage_form


class Item(models.Model):
    name = models.CharField(max_length=200)
    dosage_form = models.CharField(max_length=200, choices=DOSAGE_FORM, blank=True, null=True)
    brand = models.CharField(max_length=200, blank=True, null=True)
    unit = models.CharField(max_length=200, choices=UNIT, blank=True, null=True)
    cost = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    markup = models.DecimalField(max_digits=6, decimal_places=2, default=0, choices=MARKUP_CHOICES)
    stock = models.PositiveIntegerField(default=0, null=True, blank=True)
    low_stock_threshold = models.PositiveIntegerField(default=0, null=True, blank=True)
    exp_date = models.DateField()    
    
    class Meta:
        ordering = ('name',)
    
    def __str__(self):
        return f'{self.name} {self.brand} {self.unit} {self.cost} {self.price} {self.markup} {self.stock} {self.exp_date}'
    
    def save(self, *args, **kwargs):
        # Check if the price was provided; if not, calculate based on the markup
        if not self.price or self.price == self.cost + (self.cost * self.markup / 100):
            self.price = self.cost + (self.cost * self.markup / 100)
        super().save(*args, **kwargs)




class WholesaleItem(models.Model):
    name = models.CharField(max_length=200)
    dosage_form = models.CharField(max_length=200, choices=DOSAGE_FORM, blank=True, null=True)
    brand = models.CharField(max_length=200, blank=True, null=True)
    unit = models.CharField(max_length=200, choices=UNIT, blank=True, null=True)
    cost = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    markup = models.DecimalField(max_digits=6, decimal_places=2, default=0, choices=MARKUP_CHOICES)
    stock = models.PositiveIntegerField(default=0, null=True, blank=True)
    low_stock_threshold = models.PositiveIntegerField(default=0, null=True, blank=True)
    exp_date = models.DateField()    
    
    class Meta:
        ordering = ('name',)
    
    def __str__(self):
        return f'{self.name} {self.brand} {self.unit} {self.cost} {self.price} {self.markup} {self.stock} {self.exp_date}'
    
    def save(self, *args, **kwargs):
        # Check if the price was provided; if not, calculate based on the markup
        if not self.price or self.price == self.cost + (self.cost * self.markup / 100):
            self.price = self.cost + (self.cost * self.markup / 100)
        super().save(*args, **kwargs)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    dosage_form = models.ForeignKey(Formulation, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.CharField(max_length=200, blank=True, null=True)
    unit = models.CharField(max_length=200, choices=UNIT, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    subtotal = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    cart_id = ShortUUIDField(unique=True, length=5, max_length=50, prefix='CID: ', alphabet='1234567890')
    
    def __str__(self):
        return f'{self.cart_id} {self.user}'
    
    @property
    def calculate_subtotal(self):
        return self.price * self.quantity
    
    def save(self, *args, **kwargs):
        self.subtotal = self.calculate_subtotal
        super().save(*args, **kwargs)



class WholesaleCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    item = models.ForeignKey(WholesaleItem, on_delete=models.CASCADE)
    dosage_form = models.ForeignKey(Formulation, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.CharField(max_length=200, blank=True, null=True)
    unit = models.CharField(max_length=200, choices=UNIT, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    subtotal = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    cart_id = ShortUUIDField(unique=True, length=5, max_length=50, prefix='CID: ', alphabet='1234567890')
    
    def __str__(self):
        return f'{self.cart_id} {self.user}'
    
    @property
    def calculate_subtotal(self):
        return self.price * self.quantity
    
    def save(self, *args, **kwargs):
        self.subtotal = self.calculate_subtotal
        super().save(*args, **kwargs)



class DispensingLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    dosage_form = models.ForeignKey(Formulation, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.CharField(max_length=100, blank=True, null=True)
    unit = models.CharField(max_length=10, choices=UNIT, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=0)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Dispensed')
    created_at = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f'{self.user.username} - {self.name} {self.dosage_form} {self.brand} ({self.quantity} {self.unit} {self.status})'



# Ensure Sales is defined before Receipt
class Sales(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    wholesale_customer = models.ForeignKey(WholesaleCustomer, on_delete=models.CASCADE, null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    date = models.DateField(default=datetime.now)

    def __str__(self):
        return f'{self.user} - {self.customer.name if self.customer else "WALK-IN CUSTOMER"} - {self.total_amount}'

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new and self.customer:
            TransactionHistory.objects.create(
            customer=self.customer,
            transaction_type='purchase',
            amount=self.total_amount,
            description='Items purchased'
        )
        Receipt.objects.create(
            customer=self.customer,
            sales=self,
            total_amount=self.total_amount
        )

    def calculate_total_amount(self):
        self.total_amount = sum(item.price * item.quantity for item in self.sales_items.all())
        self.save()




# Create your models here.
class Receipt(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    sales = models.ForeignKey(Sales, on_delete=models.CASCADE, related_name='receipts', null=True, blank=True)
    buyer_name = models.CharField(max_length=255, blank=True, null=True)

pharmapp/templates/store/cart.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<style>
    .table {
        color: #333;
    }

    .container {
        display: grid;
        grid-template-columns: 1fr 5fr;
        margin-top: 0em;
    }

    .col-md-8 {
        width: 80em;
        margin-left: 2em;
    }

    .col-md-8 button,
    .col-md-8 a {
        box-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);
    }

    .side-nav {
        width: 80px;
        position: sticky;
        top: 50px;
        height: calc(100vh - 50px);
        margin-left: -2em;
    }

    .side-nav button,
    .side-nav a {
        margin: 10px;
        width: 100px;
        box-shadow: 2px 5px 5px rgba(0, 0, 0, 0.2);
    }

    /* Media query for tablets */
    @media (max-width: 768px) {
        .container {
            grid-template-columns: 1fr;
            margin-top: 0.5em;
        }

        .col-md-8 {
            width: 100%;
            margin-left: 0;
            margin-top: -23em;
        }

        .side-nav {
            margin-left: 0;
            width: 100%;
        }
    }

    /* Media query for mobile devices */
    @media (max-width: 480px) {
        .container {
            display: block;
            margin-top: 0.5em;
        }

        .col-md-8 {
            width: 100%;
            margin-left: 0;
            margin-top: -23em;
        }

        .side-nav {
            position: relative;
            width: 30%;
            margin-bottom: 0;
        }

        .side-nav button,
        .side-nav a {
            width: 100%;
        }

        .cart-table table {
            font-size: 10px;
            max-width: 70%;
        }
    }
</style>

<div class="container">
    <div class="side-nav">
        <a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#dispenseModal"
            hx-get="{% url 'store:dispense' %}" hx-target="#dispenseModal .modal-body">Select item</a>

        <a class="btn btn-sm btn-warning" href="{% url 'store:view_cart' %}">View cart</a>

        <a class="btn btn-success btn-sm" href="{% url 'store:receipt' %}">Receipt</a>

        <form method="POST" action="{% url 'store:clear_cart' %}" onsubmit="return confirmClearCart();">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-dark btn-sm">Clear Cart</button>
        </form>

        <a class="btn btn-secondary btn-sm" href="{{ request.META.HTTP_REFERER }}">Back</a>
    </div>
    <div class="col-md-8 offset-md-3 cart-table table-responsive">
        <h3 style="text-align: center;">Retail Cart</h3>
        {% for message in messages %}
        <div style="text-align: center;" class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
        {% if cart_items %}

        <div class="table-responsive">
            <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                <thead class="table-primary">
                    <tr>
                        <th scope="col">S/no</th>
                        <th scope="col">Generic</th>
                        <th scope="col">D/form</th>
                        <th scope="col">Brand</th>
                        <th scope="col">Unit</th>
                        <th scope="col">Qty</th>
                        <th scope="col">Rate</th>
                        <th scope="col">Subtotal</th>
                        <th scope="col">Reduce-by</th>
                        <!-- <th scope="col">Discount</th> -->
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cart_item.item.name|title }}</td>
                        <td>{{ cart_item.item.dosage_form }}</td>
                        <td>{{ cart_item.item.brand }}</td>
                        <td>{{ cart_item.item.unit }}</td>
                        <td>{{ cart_item.quantity }}</td>
                        <td>{{ cart_item.item.price }}</td>
                        <td>{{ cart_item.calculate_subtotal }}</td>
                        <td>
                            <form action="{% url 'store:update_cart_quantity' cart_item.id %}" method="post">
                                {% csrf_token %}
                                <input type="number" name="quantity" min="1" id="quantity-{{ cart_item.id }}"
                                    style="width: 70px; border-radius: 3px;">
                                <button class="btn btn-outline-danger btn-sm mb-2" type="submit">Reduce</button>
                            </form>
                        </td>
                        <!-- <td>
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="number" step="0.01" name="discount_amount-{{ cart_item.id }}"
                                id="discount_amount-{{cart_item.id}}" min="0" value="discount_amount-{{total_discount}}"
                                style="width: 70px; border-radius: 3px;">
                            <button class="btn btn-outline-info btn-sm mb-2" type="submit">Discount</button>
                        </form> -->
                        <!-- </td> -->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <h6>
            TOTAL PRICE: ₦ <strong>{{ total_price }}</strong>
        </h6>

        <h4>
            <!-- TOTAL AFTER DISCOUNT: ₦  -->
        </h4>
        {% else %}
        <div class="col-md-8 offset-md-3">
            <h3 style="text-align: center; color:blue">No item found in the cart</h3>
        </div>
        {% endif %}
    </div>
</div>



<script>
    function confirmClearCart() {
        return confirm("Are you sure you want to clear the cart?");
    }
</script>


<!-- Dispense Modal -->
<div class="modal fade" id="dispenseModal" tabindex="-1" aria-labelledby="dispenseModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>SELECT ITEM</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">x</button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>
{% endblock %}

pharmapp/templates/store/store.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<style>
    .table {
        color: #333
    }

    .col-md-8 {
        width: 100%;
        margin-left: -20px;
    }

    .col-md-8 button,
    .col-md-8 a {
        box-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);
    }

    .side-nav {
        width: 100px;
        position: sticky;
        top: 50px;
        height: calc(100vh - 50px);
        margin-left: 2em;
    }

    .side-nav button,
    .side-nav a {
        margin: 10px;
        width: 100px;
        box-shadow: 2px 5px 5px rgba(0, 0, 0, 0.2);
    }

    .alert-container {
        margin: 20px 0;
    }

    .alert-warning {
        background-color: #fff3cd;
        color: #856404;
        border: 1px solid #ffeeba;
        padding: 10px 15px;
        border-radius: 5px;
    }

    @media (max-width: 768px) {
        .container {
            grid-template-columns: 1fr;
        }

        .col-md-8 {
            width: 100%;
            margin-left: 0;
        }

        .side-nav {
            width: 100%;
            height: auto;
            margin-left: 0;
            margin-bottom: 1em;
        }

        .side-nav button,
        .side-nav a {
            width: 30%;
        }
    }

    @media (max-width: 480px) {
        .container {
            grid-template-columns: 1fr;
            margin-top: -2em;
        }

        .col-md-8 {
            width: 85%;
            margin-top: 1.5em;
        }

        .side-nav {
            position: relative;
            width: 100%;
            height: auto;
        }

        .side-nav button,
        .side-nav a {
            width: 30%;
            margin: 5px 0;
        }

        table {
            font-size: 0.6em;
        }

        .table th,
        .table td {
            padding: 0.5em;
        }
    }
</style>



<a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#addItemModal" type="button"
    hx-get="{% url 'store:add_item' %}" hx-target="#addItemModal .modal-content" hx-trigger="click">
    <i class="fa fa-plus"></i> Add New Item
</a>

<a class="btn btn-success btn-sm" href="{% url 'store:cart' %}">Dispense Retail</a>
<a class="btn btn-secondary btn-sm" href="{{request.META.HTTP_REFERER}}">Back</a>

<div class="alert-container">
    {% if low_stock_items %}
    <div class="alert alert-warning" role="alert">
        <strong>Restocking Alert:</strong> The following items are running low on stock:
        <ul>
            {% for item in low_stock_items %}
            <li>{{ item.name|title }} (Stock: {{ item.stock }})</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>

<div class="col-15">
    <h2 style="text-align: center;">Retail Items</h2>
    <input type="text" class="form-control mb-3 float-right" hx-get="{% url 'store:search_item' %}"
        hx-trigger="keyup changed delay:300ms" hx-target="#item-list" placeholder="Search items..." name="search"
        style="background-color: rgb(232, 253, 211); width:auto">

    {% for message in messages %}
    <div style="text-align: center;" class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    <div class="table-responsive">
        <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
            <thead class="table-secondary">
                <tr>
                    <th scope="col">ACTION</th>
                    <th scope="col">GENERIC</th>
                    <th scope="col">D/FORM</th>
                    <th scope="col">BRAND</th>
                    <th scope="col">UNIT</th>
                    {% if user.is_superuser or is_staff %}
                    <th scope="col">COST</th>
                    {% endif %}
                    <th scope="col">U/PRICE</th>
                    <th scope="col">STOCK</th>
                    <th scope="col">EXP DATE</th>
                </tr>
            </thead>
            <tfoot class="table-secondary">
                <tr>
                    <th scope="col">ACTION</th>
                    <th scope="col">GENERIC</th>
                    <th scope="col">D/FORM</th>
                    <th scope="col">BRAND</th>
                    <th scope="col">UNIT</th>
                    {% if user.is_superuser %}
                    <th scope="col">COST</th>
                    {% endif %}
                    <th scope="col">U/PRICE</th>
                    <th scope="col">STOCK</th>
                    <th scope="col">EXP DATE</th>
                </tr>
            </tfoot>
            <tbody id="item-list">
                {% for item in items %}
                <tr>
                    <td>
                        <a class="btn btn-sm btn-info" data-toggle="modal" data-target="#editModal"
                            hx-get="{% url 'store:edit_item' item.id %}" hx-target="#editModal .modal-content">Edit</a>

                        <a class="btn btn-sm btn-warning" data-toggle="modal" data-target="#returnItemModal"
                            hx-get="{% url 'store:return_item' item.id %}"
                            hx-target="#returnItemModal .modal-content">Return</a>

                        <a href="{% url 'store:delete_item' item.id %}"
                            onclick="return confirm('Are you sure you want to delete {{item.name|title}} from  Store?')"
                            class="btn btn-sm btn-danger">x</a>
                    </td>
                    <td>{{item.name|title}}</td>
                    <td>{{item.dosage_form|title}}</td>
                    <td>{{item.brand|title}}</td>
                    <td>{{item.unit}}</td>
                    {% if user.is_superuser %}
                    <td>{{item.cost}}</td>
                    {% endif %}
                    <td>{{item.price}}</td>
                    <td>{{item.stock}}</td>
                    <td>{{item.exp_date}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Add Item to Store Modal -->
<div class="modal fade" id="addItemModal" tabindex="-1" aria-labelledby="addItemModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>


<!-- Edit Item Modal -->
<div class="modal fade" id="editModal" tabindex="-1" aria-label="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>

<!-- Return Item Modal -->
<div class="modal fade" id="returnItemModal" tabindex="-1" aria-label="returnItemModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>

<script>
    function calculatePrice() {
        const cost = parseFloat(document.getElementById("cost").value) || 0;
        const markupPercentage = parseFloat(document.getElementById("markup_percentage").value) || 0;

        // Calculate price based on the cost and markup percentage
        const price = cost + (cost * markupPercentage / 100);

        // Show the calculated price in the price input field
        document.getElementById("price").value = price.toFixed(2);
    }
</script>

{% endblock %}

pharmapp/templates/store/update_low_stock_level.html
<form method="POST" hx-post="{% url 'store:update_low_stock_level' item.id %}" hx-target="this">
    {% csrf_token %}
    <div class="modal-body">
        <label for="low_stock_level">Restocking Level</label>
        <input type="number" name="low_stock_level" id="low_stock_level" class="form-control"
            value="{{ item.low_stock_level }}">
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>